-- ============================================================
-- Fix RLS policies for submissions (Sandbox Missions)
-- ============================================================
-- Ensure table exists with correct schema (in case it was partially created)
-- Note: using uuid column for student reference as per ProgrammingLab.tsx
CREATE TABLE IF NOT EXISTS "public"."submissions" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "task_id" text NOT NULL,
    "uuid" uuid NOT NULL,
    "code" text,
    "review_score" integer,
    "review_feedback" text,
    "review_metrics" jsonb,
    "student_name" text,
    "student_tsue_id" text,
    "status" text DEFAULT 'submitted',
    "submitted_at" bigint,
    UNIQUE("task_id", "uuid")
);
-- Enable RLS
ALTER TABLE "public"."submissions" ENABLE ROW LEVEL SECURITY;
-- Drop existing if any
DROP POLICY IF EXISTS "Students manage own mission submissions" ON submissions;
DROP POLICY IF EXISTS "Admins view all mission submissions" ON submissions;
-- 1. Students can do everything with their own submissions
CREATE POLICY "Students manage own mission submissions" ON "public"."submissions" FOR ALL USING (auth.uid() = uuid) WITH CHECK (auth.uid() = uuid);
-- 2. Teachers and Moderators can see all submissions
CREATE POLICY "Admins view all mission submissions" ON "public"."submissions" FOR
SELECT USING (
        EXISTS (
            SELECT 1
            FROM "public"."users"
            WHERE "public"."users"."uuid" = auth.uid()
                AND (
                    "public"."users"."role" = 'teacher'
                    OR "public"."users"."role" = 'moderator'
                )
        )
    );
-- Also fix assignment_submissions to use RLS properly with auth.uid()
-- (Already handled in previous fix, but reinforcing)
ALTER TABLE IF EXISTS "public"."assignment_submissions" ENABLE ROW LEVEL SECURITY;